name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Maven Tests
        run: mvn clean test
        env:
          MAVEN_OPTS: >-
            --add-exports jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED
            --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
