jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests with Maven
        run: mvn clean test
        env:
          MAVEN_OPTS: >-
            --add-exports jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED
